name: blindytesty
description: Use spotify, youtube or your local files to do blind tests.
publish_to: none
version: 0.1.0
environment:
  sdk: '>=2.16.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  kplayer: ^0.1.17
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.4
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  spotify: ^0.7.0
  equatable: ^2.0.3
  url_launcher: ^6.1.0
  uni_links: ^0.5.1
  dio: ^4.0.6
  dart_jsonwebtoken: ^2.4.1
  youtube_explode_dart: ^1.11.0
  path_provider: ^2.0.9
  file_picker: ^4.5.1
  window_location_href: ^1.0.0
  package_info_plus: ^1.4.2
  unofficial_jisho_api: ^3.0.0
  kana_kit: ^2.0.0
  url_strategy: ^0.2.0
  html_messages:
    path: packages/html_messages
  overlay_support: ^1.2.1
  quick_notify: ^0.2.1
  cupertino_icons: ^1.0.2
  webview_dart:
    git: https://github.com/shreyassanthu77/webview_dart
  firebase_core: ^1.16.0
  ota_update: ^4.0.1
  oauth2: ^2.0.0
  animated_overflow: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  bloc_test: ^9.0.3
  build_runner: ^2.1.10
  flutter_lints: ^2.0.1
dependency_overrides:
  dart_vlc: ^0.2.0
flutter:
  uses-material-design: true
  assets:
    - assets/spotify/Spotify_Icon_RGB_Black.png
    - assets/spotify/Spotify_Icon_RGB_Green.png
    - assets/spotify/Spotify_Icon_RGB_White.png
    - assets/spotify/Spotify_Logo_RGB_Black.png
    - assets/spotify/Spotify_Logo_RGB_Green.png
    - assets/spotify/Spotify_Logo_RGB_White.png
    - >-
      assets/youtube/youtube_monochrome_logos/digital_and_tv/yt_logo_mono_dark.png
